# Generated code do not commit.
file(TO_CMAKE_PATH "D:\\SOFTWARE\\flutter" FLUTTER_ROOT)
file(TO_CMAKE_PATH "E:\\code project\\07_Gin-Flutter-WOL\\AppGUI" PROJECT_DIR)

set(FLUTTER_VERSION "1.1.3" PARENT_SCOPE)
set(FLUTTER_VERSION_MAJOR 1 PARENT_SCOPE)
set(FLUTTER_VERSION_MINOR 1 PARENT_SCOPE)
set(FLUTTER_VERSION_PATCH 3 PARENT_SCOPE)
set(FLUTTER_VERSION_BUILD 0 PARENT_SCOPE)

# Environment variables to pass to tool_backend.sh
list(APPEND FLUTTER_TOOL_ENVIRONMENT
  "FLUTTER_ROOT=D:\\SOFTWARE\\flutter"
  "PROJECT_DIR=E:\\code project\\07_Gin-Flutter-WOL\\AppGUI"
  "FLUTTER_ROOT=D:\\SOFTWARE\\flutter"
  "FLUTTER_EPHEMERAL_DIR=E:\\code project\\07_Gin-Flutter-WOL\\AppGUI\\windows\\flutter\\ephemeral"
  "PROJECT_DIR=E:\\code project\\07_Gin-Flutter-WOL\\AppGUI"
  "FLUTTER_TARGET=lib\\main.dart"
  "DART_DEFINES=RkxVVFRFUl9WRVJTSU9OPTMuNDEuMA==,RkxVVFRFUl9DSEFOTkVMPXN0YWJsZQ==,RkxVVFRFUl9HSVRfVVJMPWh0dHBzOi8vZ2l0aHViLmNvbS9mbHV0dGVyL2ZsdXR0ZXIuZ2l0,RkxVVFRFUl9GUkFNRVdPUktfUkVWSVNJT049NDRhNjI2ZjRmMA==,RkxVVFRFUl9FTkdJTkVfUkVWSVNJT049MzQ1MmQ3MzViZA==,RkxVVFRFUl9EQVJUX1ZFUlNJT049My4xMS4w"
  "DART_OBFUSCATION=false"
  "TRACK_WIDGET_CREATION=true"
  "TREE_SHAKE_ICONS=true"
  "PACKAGE_CONFIG=E:\\code project\\07_Gin-Flutter-WOL\\AppGUI\\.dart_tool\\package_config.json"
)
