name: flutter_application_4
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
#version: 1.0.0+1
#version: 1.1.2
version: 1.1.3
environment:
  sdk: ">=2.7.0 <3.0.0"
  

dependencies:

  flutter:
    sdk: flutter
  window_size:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
      ref: f2d8aa3820fb87316516670bf4d51a74de8ac0dd



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
#  pull_to_refresh: 1.6.3
  pull_to_refresh: 1.6.5
#  web_socket_channel: ^1.1.0
  event_bus: ^1.1.1
  dio: ^3.0.10
  back_button_interceptor: ^4.3.0
  json_annotation: ^3.0.0
  fluttertoast: ^4.0.1
  date_format: ^1.0.8
  ota_update: 2.4.1
  package_info: ^0.4.1

#  socket_io_client: ^0.9.12
dev_dependencies:

  flutter_test:
    sdk: flutter
    

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
  - images/电流.png
  - images/电流2.png
  - images/电流3.png 
  - images/x轴加速度.png
  - images/y轴加速度.png
  - images/z轴加速度.png
  - images/振动加速度.png
  - images/温度.png
  - images/温度2.png
  - images/tongye2pro.png
  - images/time.png
  - images/tick.png
  - images/风机.png
  - images/当前故障.png
  - images/版本.png
  - images/当前状态.png
  - images/运行模式.png
  - images/转速.png
  - images/电压.png
  - images/累计运行时间.png
  - images/编号.png
  - images/输入源.png
  - images/上位机连接-no.png
  - images/上位机连接-yes.png
  - images/loading_idle.png
  - images/xl_loading.gif
  - images/updateBg.png
  - images/null_state08.png


  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
